// Aeroporti per l'autocompletamento: [IATA, nome, paese]. Generato dagli elenchi di Ryanair e Wizz Air più i
// principali hub; si può comunque scrivere qualunque codice IATA di 3 lettere.
export default [
  ["AAR", "Aarhus", "Danimarca"],
  ["ABZ", "Aberdeen", "Regno Unito"],
  ["AUH", "Abu Dhabi", "Emirati Arabi Uniti"],
  ["AYT", "Adalia\r\n", "Turchia"],
  ["AGA", "Agadir", "Marocco"],
  ["AES", "Alesund", "Norvegia"],
  ["ALY", "Alexandria", "Egitto"],
  ["AHO", "Alghero", "Italia"],
  ["ALC", "Alicante", "Spagna"],
  ["LEI", "Almeria", "Spagna"],
  ["HAM", "Amburgo", "Germania"],
  ["AMM", "Amman Giordania", "Giordania"],
  ["AMS", "Amsterdam", "Olanda"],
  ["AOI", "Ancona", "Italia"],
  ["ESB", "Ankara\r\n", "Turchia"],
  ["ARW", "Arad", "Romania"],
  ["OVD", "Asturie\r\n", "Spagna"],
  ["ATH", "Atene", "Grecia"],
  ["BCM", "Bacău\r\n", "Romania"],
  ["GYD", "Baku", "Azerbaigian"],
  ["BKK", "Bangkok", "Thailandia"],
  ["BNX", "Banja Luka", "Bosnia & Herzegovina"],
  ["GRO", "Barcellona (Girona)", "Spagna"],
  ["REU", "Barcellona (Reus)", "Spagna"],
  ["BCN", "Barcellona El Prat", "Spagna"],
  ["BRI", "Bari", "Italia"],
  ["MLH", "Basel Mulhouse", "Francia"],
  ["BSL", "Basilea", "Svizzera"],
  ["BFS", "Belfast International", "Regno Unito"],
  ["BEG", "Belgrado", "Serbia"],
  ["BEM", "Beni Mellal", "Marocco"],
  ["BGO", "Bergen", "Norvegia"],
  ["EGC", "Bergerac", "Francia"],
  ["BER", "Berlino Brandeburgo", "Germania"],
  ["BZR", "Beziers", "Francia"],
  ["BIQ", "Biarritz", "Francia"],
  ["BIO", "Bilbao\r\n", "Spagna"],
  ["BLL", "Billund", "Danimarca"],
  ["BHX", "Birmingham", "Regno Unito"],
  ["BJV", "Bodrum", "Turchia"],
  ["BLQ", "Bologna", "Italia"],
  ["FRL", "Bologna Forlí-Ravenna", "Italia"],
  ["BOD", "Bordeaux", "Francia"],
  ["BOS", "Boston", "Stati Uniti"],
  ["BOH", "Bournemouth", "Regno Unito"],
  ["GHV", "Brasov", "Romania"],
  ["BTS", "Bratislava", "Slovacchia"],
  ["BRE", "Brema", "Germania"],
  ["WRO", "Breslavia", "Polonia"],
  ["BDS", "Brindisi", "Italia"],
  ["BRS", "Bristol", "Regno Unito"],
  ["BVE", "Brive", "Francia"],
  ["BRQ", "Brno", "Repubblica Ceca"],
  ["CRL", "Bruxelles (Charleroi)", "Belgio"],
  ["BRU", "Bruxelles Zaventem", "Belgio"],
  ["OTP", "Bucharest (Otopeni)", "Romania"],
  ["BBU", "Bucharest Baneasa ", "Romania"],
  ["BUD", "Budapest", "Ungheria"],
  ["BOJ", "Burgas", "Bulgaria"],
  ["BZG", "Bydgoszcz", "Polonia"],
  ["CAG", "Cagliari", "Italia"],
  ["CCF", "Carcassonne", "Francia"],
  ["CWL", "Cardiff", "Regno Unito"],
  ["CMN", "Casablanca", "Marocco"],
  ["CDT", "Castellon (Valencia)", "Spagna"],
  ["CTA", "Catania", "Italia"],
  ["EFL", "Cefalonia", "Grecia"],
  ["CHQ", "Chania (Creta)", "Grecia"],
  ["RMO", "Chișinău", "Moldavia"],
  ["CLJ", "Cluj", "Romania"],
  ["CGN", "Colonia", "Germania"],
  ["CIY", "Comiso (Sicilia)\r\n", "Italia"],
  ["CPH", "Copenaghen", "Danimarca"],
  ["CFU", "Corfù", "Grecia"],
  ["ORK", "Cork", "Irlanda"],
  ["CND", "Costanza", "Romania"],
  ["KRK", "Cracovia", "Polonia"],
  ["CRA", "Craiova", "Romania"],
  ["CRV", "Crotone", "Italia"],
  ["CUF", "Cuneo", "Italia"],
  ["VIL", "Dakhla ", "Marocco"],
  ["DLM", "Dalaman", "Turchia"],
  ["GDN", "Danzica", "Polonia"],
  ["DEB", "Debrecen", "Ungheria"],
  ["LDY", "Derry", "Regno Unito"],
  ["DOH", "Doha", "Qatar"],
  ["DLE", "Dole", "Francia"],
  ["DTM", "Dortmund", "Germania"],
  ["DXB", "Dubai\r\n", "Emirati Arabi Uniti"],
  ["DUB", "Dublino", "Irlanda"],
  ["DBV", "Dubrovnik", "Croazia"],
  ["NRN", "Düsseldorf (Weeze)", "Germania"],
  ["EMA", "East Midlands", "Regno Unito"],
  ["EDI", "Edimburgo", "Regno Unito"],
  ["EIN", "Eindhoven", "Olanda"],
  ["NLM", "Eindhoven / Maastricht", "Paesi Bassi"],
  ["EVN", "Erevan", "Armenia"],
  ["ERH", "Errachidia", "Marocco"],
  ["ESU", "Essaouira", "Marocco"],
  ["EXT", "Exeter", "Regno Unito"],
  ["FAO", "Faro", "Portogallo"],
  ["FEZ", "Fez", "Marocco"],
  ["FSC", "Figari", "Francia"],
  ["FLR", "Firenze", "Italia"],
  ["RJK", "Fiume", "Croazia"],
  ["FRA", "Francoforte", "Germania"],
  ["HHN", "Francoforte (Hahn)", "Germania"],
  ["FDH", "Friedrichshafen", "Germania"],
  ["FUE", "Fuerteventura", "Spagna"],
  ["JED", "Gedda\r\n", "Arabia Saudita"],
  ["GOA", "Genova", "Italia"],
  ["GVA", "Ginevra", "Svizzera"],
  ["GLA", "Glasgow", "Regno Unito"],
  ["PIK", "Glasgow (Prestwick)", "Regno Unito"],
  ["LPA", "Gran Canaria", "Spagna"],
  ["GRX", "Granada\r\n", "Spagna"],
  ["GNB", "Grenoble", "Francia"],
  ["LWN", "Gyumri", "Armenia"],
  ["GOT", "Göteborg Landvetter", "Svezia"],
  ["HAU", "Haugesund", "Norvegia"],
  ["HEL", "Helsinki", "Finlandia"],
  ["HER", "Heraklion Creta", "Grecia"],
  ["HRG", "Hurghada", "Egitto"],
  ["IAS", "Iasi", "Romania"],
  ["IBZ", "Ibiza", "Spagna"],
  ["CAI", "Il Cairo", "Egitto"],
  ["SPX", "Il Cairo (Sfinge)", "Egitto"],
  ["IST", "Istanbul\r\n", "Turchia"],
  ["KLX", "Kalamata", "Grecia"],
  ["FKB", "Karlsruhe / Baden-Baden", "Germania"],
  ["KTW", "Katowice", "Polonia"],
  ["KUN", "Kaunas", "Lituania"],
  ["KIR", "Kerry", "Irlanda"],
  ["KLU", "Klagenfurt", "Austria"],
  ["NOC", "Knock-Irlanda dell ovest", "Irlanda"],
  ["KGS", "Kos", "Grecia"],
  ["KSC", "Kosice", "Slovacchia"],
  ["KUT", "Kutaisi", "Georgia"],
  ["LRH", "La Rochelle", "Francia"],
  ["SUF", "Lamezia", "Italia"],
  ["LMP", "Lampedusa", "Italia"],
  ["ACE", "Lanzarote", "Spagna"],
  ["LCA", "Larnaca", "Cipro"],
  ["LBA", "Leeds Bradford", "Regno Unito"],
  ["LXS", "Lemnos", "Grecia"],
  ["LIL", "Lille", "Francia"],
  ["LIG", "Limoges", "Francia"],
  ["LNZ", "Linz", "Austria"],
  ["LYS", "Lione\r\n", "Francia"],
  ["LIS", "Lisbona", "Portogallo"],
  ["LPL", "Liverpool", "Regno Unito"],
  ["LCJ", "Lodz", "Polonia"],
  ["LGW", "Londra (Gatwick)", "Regno Unito"],
  ["LTN", "Londra (Luton)", "Regno Unito"],
  ["STN", "Londra (Stansted)", "Regno Unito"],
  ["LON", "Londra (tutti gli aeroporti)", "Regno Unito"],
  ["LCY", "Londra City", "Regno Unito"],
  ["LHR", "Londra Heathrow", "Regno Unito"],
  ["LAX", "Los Angeles", "Stati Uniti"],
  ["LDE", "Lourdes", "Francia"],
  ["LBC", "Lubeck", "Germania"],
  ["LJU", "Lubiana", "Slovenia"],
  ["LUZ", "Lublino", "Polonia"],
  ["LUX", "Lussemburgo", "Lussemburgo"],
  ["MST", "Maastricht", "Paesi Bassi"],
  ["FNC", "Madeira Funchal", "Portogallo"],
  ["MAD", "Madrid", "Spagna"],
  ["AGP", "Malaga", "Spagna"],
  ["MMX", "Malmö", "Svezia"],
  ["MLA", "Malta", "Malta"],
  ["MLE", "Malé (Maldive)", "Maldive"],
  ["MAN", "Manchester", "Regno Unito"],
  ["RAK", "Marrakech", "Marocco"],
  ["RMF", "Marsa Alam\r\n", "Egitto"],
  ["MRS", "Marsiglia", "Francia"],
  ["FMM", "Memmingen", "Germania"],
  ["MIA", "Miami", "Stati Uniti"],
  ["MIL", "Milano (tutti gli aeroporti)", "Italia"],
  ["BGY", "Milano Bergamo", "Italia"],
  ["LIN", "Milano Linate", "Italia"],
  ["MXP", "Milano Malpensa", "Italia"],
  ["MAH", "Minorca", "Spagna"],
  ["MUC", "Monaco di Baviera", "Germania"],
  ["RMU", "Murcia International", "Spagna"],
  ["JMK", "Mykonos", "Grecia"],
  ["FMO", "Münster", "Germania"],
  ["NDR", "Nador", "Marocco"],
  ["NTE", "Nantes", "Francia"],
  ["NAP", "Napoli", "Italia"],
  ["JFK", "New York JFK", "Stati Uniti"],
  ["EWR", "New York Newark", "Stati Uniti"],
  ["NCL", "Newcastle", "Regno Unito"],
  ["NQY", "Newquay Cornovaglia", "Regno Unito"],
  ["FNI", "Nimes", "Francia"],
  ["INI", "Nis", "Serbia"],
  ["NCE", "Nizza", "Francia"],
  ["NUE", "Norimberga", "Germania"],
  ["NWI", "Norwich", "Regno Unito"],
  ["OHD", "Ocrida", "Macedonia del Nord"],
  ["OLB", "Olbia", "Italia"],
  ["SZY", "Olsztyn - Mazury", "Polonia"],
  ["OMR", "Oradea\r\n", "Romania"],
  ["OSI", "Osijek", "Croazia"],
  ["OSL", "Oslo", "Norvegia"],
  ["TRF", "Oslo (Torp)", "Norvegia"],
  ["OOS", "Oslo (tutti gli aeroporti)", "Norvegia"],
  ["OSR", "Ostrava", "Repubblica Ceca"],
  ["OZZ", "Ouarzazate", "Marocco"],
  ["OUD", "Oujda", "Marocco"],
  ["PAD", "Paderborn", "Germania"],
  ["PFO", "Pafos", "Cipro"],
  ["PLQ", "Palanga", "Lituania"],
  ["PMO", "Palermo", "Italia"],
  ["PMI", "Palma", "Spagna"],
  ["PED", "Pardubice", "Repubblica Ceca"],
  ["BVA", "Parigi (Beauvais)", "Francia"],
  ["PAR", "Parigi (tutti gli aeroporti)", "Francia"],
  ["XCR", "Parigi (Vatry)", "Francia"],
  ["CDG", "Parigi Charles de Gaulle", "Francia"],
  ["ORY", "Parigi Orly", "Francia"],
  ["PMF", "Parma", "Italia"],
  ["PGF", "Perpignan", "Francia"],
  ["PEG", "Perugia", "Italia"],
  ["PSR", "Pescara", "Italia"],
  ["PSA", "Pisa", "Italia"],
  ["PDV", "Plovdiv", "Bulgaria"],
  ["TGD", "Podgorica", "Montenegro"],
  ["PIS", "Poitiers", "Francia"],
  ["PUY", "Pola", "Croazia"],
  ["TAT", "Poprad-Tatry", "Slovacchia"],
  ["OPO", "Porto", "Portogallo"],
  ["POZ", "Poznan", "Polonia"],
  ["PRG", "Praga", "Repubblica Ceca"],
  ["PVK", "Preveza - Aktion", "Grecia"],
  ["PRN", "Pristina", "Kosovo"],
  ["RBA", "Rabat", "Marocco"],
  ["REG", "Reggio Calabria", "Italia"],
  ["KEF", "Reykjavik", "Islanda"],
  ["REK", "Reykjavik", "Islanda"],
  ["RIX", "Riga", "Lettonia"],
  ["RMI", "Rimini", "Italia"],
  ["RDZ", "Rodez", "Francia"],
  ["RHO", "Rodi", "Grecia"],
  ["CIA", "Roma (Ciampino)", "Italia"],
  ["FCO", "Roma (Fiumicino)", "Italia"],
  ["ROM", "Roma (tutti gli aeroporti)", "Italia"],
  ["RVN", "Rovaniemi - Lapponia", "Finlandia"],
  ["RZE", "Rzeszow", "Polonia"],
  ["SCN", "Saarbrücken", "Germania"],
  ["QSR", "Salerno Costa d'Amalfi", "Italia"],
  ["SZG", "Salisburgo", "Austria"],
  ["SKG", "Salonicco", "Grecia"],
  ["SDR", "Santander", "Spagna"],
  ["SCQ", "Santiago", "Spagna"],
  ["JTR", "Santorini Nazionale", "Grecia"],
  ["ZAZ", "Saragozza", "Spagna"],
  ["SJJ", "Sarajevo", "Bosnia & Herzegovina"],
  ["SUJ", "Satu Mare", "Romania"],
  ["SNN", "Shannon", "Irlanda"],
  ["SSH", "Sharm El Sheikh\r\n", "Egitto"],
  ["SBZ", "Sibiu", "Romania"],
  ["SIN", "Singapore", "Singapore"],
  ["SVQ", "Siviglia", "Spagna"],
  ["SFT", "Skelleftea", "Svezia"],
  ["JSI", "Skiathos", "Grecia"],
  ["SKP", "Skopje", "Macedonia del Nord"],
  ["SOF", "Sofia", "Bulgaria"],
  ["SPU", "Spalato", "Croazia"],
  ["SVG", "Stavanger", "Norvegia"],
  ["SZZ", "Stettino", "Polonia"],
  ["STR", "Stoccarda", "Germania"],
  ["STO", "Stoccolma (tutti gli aeroporti)", "Svezia"],
  ["ARN", "Stoccolma Arlanda", "Svezia"],
  ["NYO", "Stoccolma Skavsta\r\n", "Svezia"],
  ["VST", "Stoccolma Västerås", "Svezia"],
  ["SCV", "Suceava", "Romania"],
  ["TLL", "Tallinn", "Estonia"],
  ["TNG", "Tangeri", "Marocco"],
  ["MME", "Teesside", "Regno Unito"],
  ["TLV", "Tel Aviv\r\n", "Israele"],
  ["TFS", "Tenerife (Sud)", "Spagna"],
  ["TFN", "Tenerife Nord (Isole Canarie)\r\n", "Spagna"],
  ["TSR", "Timisoara", "Romania"],
  ["TIA", "Tirana", "Albania"],
  ["TGM", "Tirgu Mures", "Romania"],
  ["HND", "Tokyo Haneda", "Giappone"],
  ["NRT", "Tokyo Narita", "Giappone"],
  ["TLS", "Tolosa", "Francia"],
  ["TRN", "Torino", "Italia"],
  ["YYZ", "Toronto", "Canada"],
  ["TUF", "Tours Valle della Loira", "Francia"],
  ["TPS", "Trapani-Marsala", "Italia"],
  ["TRS", "Trieste", "Italia"],
  ["TOS", "Tromso\r\n", "Norvegia"],
  ["TRD", "Trondheim", "Norvegia"],
  ["TKU", "Turku", "Finlandia"],
  ["TZL", "Tuzla", "Bosnia ed Erzegovina"],
  ["TTU", "Tétouan", "Marocco"],
  ["VLC", "Valencia", "Spagna"],
  ["VAR", "Varna", "Bulgaria"],
  ["WAW", "Varsavia (Chopin)", "Polonia"],
  ["WMI", "Varsavia (Modlin)", "Polonia"],
  ["RDO", "Varsavia Radom\r\n", "Polonia"],
  ["TSF", "Venezia (Treviso)", "Italia"],
  ["VEN", "Venezia (tutti gli aeroporti)", "Italia"],
  ["VCE", "Venezia M.Polo", "Italia"],
  ["VRN", "Verona", "Italia"],
  ["VIE", "Vienna", "Austria"],
  ["VNO", "Vilnius", "Lituania"],
  ["VIT", "Vitoria", "Spagna"],
  ["VOL", "Volos", "Grecia"],
  ["VXO", "Växjö Småland", "Svezia"],
  ["WSW", "Warsaw Any", "Polonia"],
  ["ZTH", "Zacinto", "Grecia"],
  ["ZAG", "Zagabria", "Croazia"],
  ["ZAD", "Zara", "Croazia"],
  ["ZRH", "Zurigo", "Svizzera"],
]
